FROM openknowledge/ckan-dev:2.8

MAINTAINER Andres Vazquez <andres.vazquez@datopian.com>

# Set timezone
ARG TZ
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone

# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

ADD https://raw.githubusercontent.com/ckan/ckanext-harvest/master/pip-requirements.txt /src/harvest-reqs.txt
ADD https://raw.githubusercontent.com/GSA/ckanext-datajson/datagov/requirements.txt /src/datajson-reqs.txt

RUN pip install --upgrade pip && \
    pip install -r /src/harvest-reqs.txt && \
    pip install -r /src/datajson-reqs.txt && \
    pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest && \
    pip install -e git+https://github.com/gsa/ckanext-datajson.git@datagov#egg=ckanext-datajson

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
# See https://github.com/okfn/docker-ckan#applying-patches
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done

COPY docker-entrypoint.d/* /docker-entrypoint.d/